apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mguay/ordering-app_auth
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  key: MONGO_PORT
                  name: secret-config
            - name: RABBIT_MQ_BILLING_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: RABBIT_MQ_BILLING_QUEUE
                  name: config-all
            - name: RABBIT_MQ_AUTH_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: RABBIT_MQ_AUTH_QUEUE
                  name: config-all
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: secret-config
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  key: JWT_EXPIRATION
                  name: secret-config
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: MONGODB_URI
                  name: secret-config
            - name: RABBIT_MQ_URI
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_URI
                  name: secret-config