apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: mguay/ordering-app_billing
          env:
            - name: RABBIT_MQ_BILLING_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: RABBIT_MQ_BILLING_QUEUE
                  name: config-all
            - name: RABBIT_MQ_AUTH_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: RABBIT_MQ_AUTH_QUEUE
                  name: config-all
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: MONGODB_URI
                  name: secret-config
            - name: RABBIT_MQ_URI
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_URI
                  name: secret-config