apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: mguay/ordering-app_orders
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  key: MONGO_PORT
                  name: secret-config
            - name: RABBIT_MQ_BILLING_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: RABBIT_MQ_BILLING_QUEUE
                  name: config-all
            - name: RABBIT_MQ_AUTH_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: RABBIT_MQ_AUTH_QUEUE
                  name: config-all
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: MONGODB_URI
                  name: secret-config
            - name: RABBIT_MQ_URI
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_URI
                  name: secret-config
              